name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  kubernetes:
    strategy:
      matrix:
        version: [1.27.10, 1.28.6, 1.29.1]
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.21.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Kubernetes
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          version: v0.20.0
          node_image: kindest/node:v${{ matrix.version }}
          cluster_name: kind
          kubectl_version: v${{ matrix.version }}
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Push module
        run: |
          timoni mod push ./ oci://localhost:5000/trust-manager -v 1.0.0 --latest
      - name: Install cert-manager module
        run: |
          timoni -n test apply cert-manager oci://ghcr.io/nalum/timoni/modules/cert-manager
      - name: Install module
        run: |
          timoni -n test apply trust-manager oci://localhost:5000/trust-manager
      - name: List modules
        run: |
          timoni list -A
      - name: Upgrade module with custom values
        run: |
          echo 'values: logLevel: 6' | timoni -n test apply trust-manager oci://localhost:5000/trust-manager -v 1.0.0 -f-
      - name: Upgrade module with debug values
        run: |
          timoni -n test apply trust-manager oci://localhost:5000/trust-manager -f ./debug_values.cue
      - name: Inspect module
        run: |
          timoni -n test inspect resources trust-manager
          timoni -n test inspect module trust-manager
          timoni -n test inspect values trust-manager
      - name: Status module
        run: |
          timoni -n test status trust-manager
      - name: Uninstall module
        run: |
          timoni -n test delete trust-manager --wait
      - name: Uninstall cert-manager module
        run: |
          timoni -n test delete cert-manager --wait
